//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class cliente
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public cliente()
    {
        this.facturacion = new HashSet<facturacion>();
    }

    public int idcliente { get; set; }
    public int idtipocliente { get; set; }
    public string codigo_cliente { get; set; }
    public string dui { get; set; }
    public string nit { get; set; }
    public string apellidos { get; set; }
    public string nombres { get; set; }
    public string sexo { get; set; }
    public string numero_telefono { get; set; }
    public string estado { get; set; }

    public virtual tipo_clientes tipo_clientes { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<facturacion> facturacion { get; set; }
}

public partial class facturacion
{
    public int idfacturacion { get; set; }
    public int idcliente { get; set; }
    public decimal monto_facturacion { get; set; }

    public virtual cliente cliente { get; set; }
}

public partial class tipo_clientes
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tipo_clientes()
    {
        this.cliente = new HashSet<cliente>();
    }

    public int idtipocliente { get; set; }
    public string nombre_tipo { get; set; }
    public string Descripcion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<cliente> cliente { get; set; }
}
