/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion;

import aplicacion.submenu.ListaAlumnos;
import aplicacion.submenu.ListaMateria;
import aplicacion.submenu.NuevaMateria;
import aplicacion.submenu.NuevoAlumno;

/**
 *
 * @author MekakuZero
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    public App() {
        initComponents();
    }

    private NuevoAlumno nuevoalumno;
    private ListaAlumnos listaalumno;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        emAlumnos = new javax.swing.JMenu();
        miNuevoAlumno = new javax.swing.JMenuItem();
        miListaAlumno = new javax.swing.JMenuItem();
        emMaterias = new javax.swing.JMenu();
        miNuevaMateria = new javax.swing.JMenuItem();
        miListaMateria = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        emAlumnos.setMnemonic('e');
        emAlumnos.setText("Alumnos");

        miNuevoAlumno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        miNuevoAlumno.setText("Nuevo alumno");
        miNuevoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNuevoAlumnoActionPerformed(evt);
            }
        });
        emAlumnos.add(miNuevoAlumno);

        miListaAlumno.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        miListaAlumno.setText("Lista de los alumnos");
        miListaAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListaAlumnoActionPerformed(evt);
            }
        });
        emAlumnos.add(miListaAlumno);

        menuBar.add(emAlumnos);

        emMaterias.setText("Materias");

        miNuevaMateria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        miNuevaMateria.setText("Nueva materia");
        miNuevaMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNuevaMateriaActionPerformed(evt);
            }
        });
        emMaterias.add(miNuevaMateria);

        miListaMateria.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        miListaMateria.setText("Ver lista de materias");
        miListaMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListaMateriaActionPerformed(evt);
            }
        });
        emMaterias.add(miListaMateria);

        menuBar.add(emMaterias);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miNuevaMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNuevaMateriaActionPerformed
        // Agregamos una nueva materia
        if (!NuevaMateria.Bandera()){
            NuevaMateria nm = new NuevaMateria();
            this.desktopPane.add(nm);
            nm.show();
        }
    }//GEN-LAST:event_miNuevaMateriaActionPerformed

    private void miListaMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListaMateriaActionPerformed
        // TODO add your handling code here:
        if (!ListaMateria.Bandera()){
            ListaMateria lm = new ListaMateria(this.desktopPane);
            this.desktopPane.add(lm);
            lm.show();
        }
    }//GEN-LAST:event_miListaMateriaActionPerformed

    private void miNuevoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNuevoAlumnoActionPerformed
        // TODO add your handling code here:
        NuevoAlumno na = new NuevoAlumno();
        this.desktopPane.add(na);
        na.show();
    }//GEN-LAST:event_miNuevoAlumnoActionPerformed

    private void miListaAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListaAlumnoActionPerformed
        // TODO add your handling code here:
        ListaAlumnos la = new ListaAlumnos(this.desktopPane);
        this.desktopPane.add(la);
        la.show();
    }//GEN-LAST:event_miListaAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu emAlumnos;
    private javax.swing.JMenu emMaterias;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem miListaAlumno;
    private javax.swing.JMenuItem miListaMateria;
    private javax.swing.JMenuItem miNuevaMateria;
    private javax.swing.JMenuItem miNuevoAlumno;
    // End of variables declaration//GEN-END:variables

}
