/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sv.edu.udb.guia5poo1.complementario;

/**
 *
 * @author MekakuZero
 */
public class Ejercicio1_Imagenes extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ejercicio1_Imagenes
     */
    public Ejercicio1_Imagenes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOpcion2 = new javax.swing.JRadioButton();
        btnOpcion3 = new javax.swing.JRadioButton();
        lblImg = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        btnOpcion1 = new javax.swing.JRadioButton();

        btnOpcion2.setText("Galaxia");
        btnOpcion2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcion2ActionPerformed(evt);
            }
        });

        btnOpcion3.setText("Nebulosa");
        btnOpcion3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcion3ActionPerformed(evt);
            }
        });

        lblTitulo.setText("Seleccionar una imagen:");

        btnOpcion1.setText("Estrella");
        btnOpcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpcion1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lblTitulo)
                        .addGap(0, 194, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnOpcion1)
                            .addComponent(btnOpcion2)
                            .addComponent(btnOpcion3))
                        .addGap(27, 27, 27)
                        .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnOpcion1)
                        .addGap(18, 18, 18)
                        .addComponent(btnOpcion2)
                        .addGap(18, 18, 18)
                        .addComponent(btnOpcion3))
                    .addComponent(lblImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOpcion2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcion2ActionPerformed
        // TODO add your handling code here:
        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sv/edu/udb/guia5poo1/complementario/img/img2.jpg")));
    }//GEN-LAST:event_btnOpcion2ActionPerformed

    private void btnOpcion3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcion3ActionPerformed
        // TODO add your handling code here:
        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sv/edu/udb/guia5poo1/complementario/img/img3.jpg")));
    }//GEN-LAST:event_btnOpcion3ActionPerformed

    private void btnOpcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpcion1ActionPerformed
        // TODO add your handling code here:
        lblImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sv/edu/udb/guia5poo1/complementario/img/img1.png")));
    }//GEN-LAST:event_btnOpcion1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnOpcion1;
    private javax.swing.JRadioButton btnOpcion2;
    private javax.swing.JRadioButton btnOpcion3;
    private javax.swing.JLabel lblImg;
    private javax.swing.JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
}
