//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class cuentas
{
    public string numero_cuenta { get; set; }
    public string nombre_propietario { get; set; }
    public Nullable<decimal> saldo { get; set; }
    public string pin { get; set; }
}
