/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacion.submenu;

import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import mojica.alexander.consulta.Conexion;
import mojica.alexander.consulta.Query;
import mojica.alexander.utilidades.*;

/**
 *
 * @author MekakuZero
 */
public class NuevoAlumno extends javax.swing.JInternalFrame {

    private int indiceEliminar = -1;
    private int filaEliminar = -1;
    private List<Integer> indicesUsados;
    private Tabla materias;
    
    /**
     * Creates new form NuevaMateria
     */
    public NuevoAlumno() {
        initComponents();
        this.tblMateriasCursadas.getColumnModel().getColumn(0).setMinWidth(0);
        this.tblMateriasCursadas.getColumnModel().getColumn(0).setMaxWidth(0);
        ObtenerMaterias();
    }

    // Obtenemos todas las materias
    public void ObtenerMaterias(){
        Conexion conexion;
        indicesUsados = new ArrayList<>();
        
        // Mientras no se haya oriducido ningun error
        if ((conexion = Conexion.establecerConexion()) != null) {
            ResultSet select = conexion.crearQuery("materia").select();
            
            this.cmbMateriasACursar.removeAllItems();
            
            try{
                while(select.next()){
                    this.cmbMateriasACursar.addItem(select.getString("Nombre"));
                }
                
                select.beforeFirst();
                materias = new Tabla(select);
                
                conexion.cerrarConexion();
                
            } catch(Exception ex){  }
            
            conexion.cerrarConexion();
            
        }
    }
    
    public void Limipiar(){
        this.txtId.setText("");
        this.txtNombre.setText("");
        this.txtApellido.setText("");
        this.btnEliminar.setEnabled(false);
        DefaultTableModel model = (DefaultTableModel)this.tblMateriasCursadas.getModel();
        
        int size = model.getRowCount();
        for (int i = 0; i < size; i++)
            model.removeRow(0);
        
        this.indicesUsados.clear();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        cmbMateriasACursar = new javax.swing.JComboBox<>();
        btnCursarMateria = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMateriasCursadas = new javax.swing.JTable();
        lblIngresoMateria = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setClosable(true);
        setIconifiable(true);
        setTitle("Nuevo alumno");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        lblId.setText("Codigo alumno:");

        txtId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdKeyTyped(evt);
            }
        });

        lblNombre.setText("Nombre del alumno:");

        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Textbox_KeyTyped(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lblApellido.setText("Apellido del alumno:");

        txtApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidoTextbox_KeyTyped(evt);
            }
        });

        cmbMateriasACursar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnCursarMateria.setText("Cursar");
        btnCursarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCursarMateriaActionPerformed(evt);
            }
        });

        tblMateriasCursadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Materia"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMateriasCursadas.setColumnSelectionAllowed(true);
        tblMateriasCursadas.getTableHeader().setReorderingAllowed(false);
        tblMateriasCursadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMateriasCursadasMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblMateriasCursadas);
        tblMateriasCursadas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblMateriasCursadas.getColumnModel().getColumnCount() > 0) {
            tblMateriasCursadas.getColumnModel().getColumn(0).setResizable(false);
            tblMateriasCursadas.getColumnModel().getColumn(1).setResizable(false);
        }

        lblIngresoMateria.setText("Materias a ingresar:");

        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblId)
                            .addComponent(lblNombre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnGuardar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnLimpiar))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(lblIngresoMateria)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addComponent(cmbMateriasACursar, 0, 213, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnCursarMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(lblApellido)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblApellido)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMateriasACursar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIngresoMateria)
                    .addComponent(btnCursarMateria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        this.Limipiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdKeyTyped
        // TODO add your handling code here:
        if (!Character.isDigit(evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_txtIdKeyTyped

    private void Textbox_KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Textbox_KeyTyped
        // TODO add your handling code here:
        if (!Character.isLetterOrDigit(evt.getKeyChar()) && evt.getKeyChar()!= ' ')
            evt.consume();
    }//GEN-LAST:event_Textbox_KeyTyped

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (Validacion.ComprobarDatosTextBox(new javax.swing.JTextField[]{ this.txtId, this.txtNombre, this.txtApellido})) {
            Conexion conexion;
            
            // Mientras no se haya oriducido ningun error
            if ((conexion = Conexion.establecerConexion()) != null) {
                
                // Informacion del usuario
                int indice = Integer.valueOf(this.txtId.getText().trim());
                String nombre = this.txtNombre.getText().trim();
                String apellido = this.txtApellido.getText().trim();
                
                
                try{
                    
                    int num = conexion.crearQuery("alumno").agregarCampoValor("Cod_alumno", indice).agregarCampoValor("Nombres", nombre).agregarCampoValor("Apellidos", apellido).insert();
                    
                    if (num > 0) {
                        
                        DefaultTableModel model = (DefaultTableModel)this.tblMateriasCursadas.getModel();
                        
                        boolean res = true;
                        
                        for (int i = 0; i < model.getRowCount(); i++) {
                            int val = Integer.valueOf(model.getValueAt(i, 0).toString());
                            
                            int id = Integer.valueOf(this.materias.getField(val, "Cod_materia"));
                            
                           int r = conexion.crearQuery("alumno_materia").agregarCampoValor("Cod_alumno", indice).agregarCampoValor("Cod_materia", id).insert();
                        
                           if (r <= 0){
                               res = false;
                               Mensaje.Error("No se ha podido guardar el alumno", title);
                               break;
                           }
                        }
                        
                        if (res){
                            Mensaje.Informacion("El usuario ha sido ingresado", title);
                            this.Limipiar();
                            this.dispose();
                        }
                        
                    } else
                        Mensaje.Error("No se ha podido guardar el alumno", title);
                    
                } catch(Exception ex){}
                
                conexion.cerrarConexion();
            } else
                Mensaje.Error("No se ha podido establecer la conexion", this.getTitle());
        } else
            Mensaje.Error("Todos los campos son obligatorios", this.getTitle());
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void txtApellidoTextbox_KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidoTextbox_KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoTextbox_KeyTyped

    private void btnCursarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCursarMateriaActionPerformed
        // TODO add your handling code here:
        int indice = this.cmbMateriasACursar.getSelectedIndex();
        
        if (!this.indicesUsados.contains(indice)) {
            String cor = this.materias.getField(indice, "Indice");
            String nombre = this.materias.getField(indice, "Nombre");

            DefaultTableModel model = (DefaultTableModel) this.tblMateriasCursadas.getModel();
            model.addRow(new Object[]{ cor, nombre });

            this.indicesUsados.add(indice);
        } else
            Mensaje.Error("La materia " + this.cmbMateriasACursar.getSelectedItem().toString() + " ya ha sido registrada", title);
    }//GEN-LAST:event_btnCursarMateriaActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        DefaultTableModel modal = (DefaultTableModel)this.tblMateriasCursadas.getModel();
        modal.removeRow(this.filaEliminar);
        this.indicesUsados.remove(this.indiceEliminar);
        this.btnEliminar.setEnabled(false);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formMouseClicked

    private void tblMateriasCursadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMateriasCursadasMouseClicked
        // TODO add your handling code here:
        DefaultTableModel modal = (DefaultTableModel)this.tblMateriasCursadas.getModel();
        this.filaEliminar = this.jTable1.rowAtPoint(evt.getPoint());
        String ind = modal.getValueAt(this.filaEliminar, 0).toString();
        this.indiceEliminar = Integer.valueOf(ind);
        this.btnEliminar.setEnabled(true);
    }//GEN-LAST:event_tblMateriasCursadasMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCursarMateria;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JComboBox<String> cmbMateriasACursar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblIngresoMateria;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JTable tblMateriasCursadas;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
