/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo_catedra_2.autores;

import mojica.lemus.utilitades.Mensaje;
import mojica.lemus.utilitades.Validacion;
import mojica.lemus.utilitades.Variados;

/**
 *
 * @author MekakuZero
 */
public class jfrm_Listar_Autores extends javax.swing.JInternalFrame {

    /**
     * Creates new form jfrm_Listar_Autores
     */
    public jfrm_Listar_Autores() {
        initComponents();
        this.pnl_datos.setVisible(false);
        Variados.botonTransparente(this.btn_cerrar);
        Variados.botonTransparente(this.btn_eliminar);
        Variados.botonTransparente(this.btn_modificar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lbl_filtro_nombre_completo = new javax.swing.JLabel();
        txt_filtro_nombre_completo = new javax.swing.JTextField();
        lbl_filtro_seudonimo = new javax.swing.JLabel();
        txt_filtro_seudonimo = new javax.swing.JTextField();
        pnl_datos = new javax.swing.JPanel();
        pnl_opciones = new javax.swing.JPanel();
        btn_cerrar = new javax.swing.JButton();
        pnl_acciones = new javax.swing.JPanel();
        btn_modificar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        pnl_info_autor = new javax.swing.JPanel();
        lbl_author = new javax.swing.JLabel();
        lbl_nombre_completo = new javax.swing.JLabel();
        txt_nombre_completo = new javax.swing.JTextField();
        lbl_seudonimo = new javax.swing.JLabel();
        txt_seudonimo = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_autores = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Autores");

        jPanel1.setBackground(new java.awt.Color(47, 54, 64));
        jPanel1.setMaximumSize(new java.awt.Dimension(479, 40));
        jPanel1.setMinimumSize(new java.awt.Dimension(479, 40));
        jPanel1.setPreferredSize(new java.awt.Dimension(479, 40));

        lbl_filtro_nombre_completo.setBackground(new java.awt.Color(255, 255, 255));
        lbl_filtro_nombre_completo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_filtro_nombre_completo.setText("Nombre del autor:");
        jPanel1.add(lbl_filtro_nombre_completo);

        txt_filtro_nombre_completo.setMaximumSize(new java.awt.Dimension(150, 25));
        txt_filtro_nombre_completo.setMinimumSize(new java.awt.Dimension(150, 25));
        txt_filtro_nombre_completo.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel1.add(txt_filtro_nombre_completo);

        lbl_filtro_seudonimo.setBackground(new java.awt.Color(255, 255, 255));
        lbl_filtro_seudonimo.setForeground(new java.awt.Color(255, 255, 255));
        lbl_filtro_seudonimo.setText("Seudonimo del autor:");
        jPanel1.add(lbl_filtro_seudonimo);

        txt_filtro_seudonimo.setMaximumSize(new java.awt.Dimension(150, 25));
        txt_filtro_seudonimo.setMinimumSize(new java.awt.Dimension(150, 25));
        txt_filtro_seudonimo.setPreferredSize(new java.awt.Dimension(150, 25));
        jPanel1.add(txt_filtro_seudonimo);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        pnl_datos.setMaximumSize(new java.awt.Dimension(160, 379));
        pnl_datos.setMinimumSize(new java.awt.Dimension(160, 379));
        pnl_datos.setPreferredSize(new java.awt.Dimension(160, 379));
        pnl_datos.setLayout(new java.awt.BorderLayout());

        pnl_opciones.setBackground(new java.awt.Color(255, 255, 255));
        pnl_opciones.setMaximumSize(new java.awt.Dimension(160, 30));
        pnl_opciones.setMinimumSize(new java.awt.Dimension(160, 30));
        pnl_opciones.setPreferredSize(new java.awt.Dimension(160, 30));

        btn_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poo_catedra_2/img/close.png"))); // NOI18N
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_opcionesLayout = new javax.swing.GroupLayout(pnl_opciones);
        pnl_opciones.setLayout(pnl_opcionesLayout);
        pnl_opcionesLayout.setHorizontalGroup(
            pnl_opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_opcionesLayout.createSequentialGroup()
                .addGap(0, 103, Short.MAX_VALUE)
                .addComponent(btn_cerrar))
        );
        pnl_opcionesLayout.setVerticalGroup(
            pnl_opcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_opcionesLayout.createSequentialGroup()
                .addComponent(btn_cerrar)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnl_datos.add(pnl_opciones, java.awt.BorderLayout.PAGE_START);

        pnl_acciones.setBackground(new java.awt.Color(194, 54, 22));
        pnl_acciones.setMaximumSize(new java.awt.Dimension(160, 40));
        pnl_acciones.setMinimumSize(new java.awt.Dimension(160, 40));
        pnl_acciones.setPreferredSize(new java.awt.Dimension(160, 40));
        pnl_acciones.setLayout(new java.awt.GridLayout(1, 0));

        btn_modificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poo_catedra_2/img/update.png"))); // NOI18N
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });
        pnl_acciones.add(btn_modificar);

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poo_catedra_2/img/delete.png"))); // NOI18N
        pnl_acciones.add(btn_eliminar);

        pnl_datos.add(pnl_acciones, java.awt.BorderLayout.PAGE_END);

        pnl_info_autor.setBackground(new java.awt.Color(255, 255, 255));
        pnl_info_autor.setLayout(new java.awt.GridBagLayout());

        lbl_author.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poo_catedra_2/img/Author.png"))); // NOI18N
        pnl_info_autor.add(lbl_author, new java.awt.GridBagConstraints());

        lbl_nombre_completo.setText("Nombre del autor:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        pnl_info_autor.add(lbl_nombre_completo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnl_info_autor.add(txt_nombre_completo, gridBagConstraints);

        lbl_seudonimo.setText("Seudonimo:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        pnl_info_autor.add(lbl_seudonimo, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        pnl_info_autor.add(txt_seudonimo, gridBagConstraints);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(5, 5));
        jPanel2.setMinimumSize(new java.awt.Dimension(5, 5));
        jPanel2.setPreferredSize(new java.awt.Dimension(5, 5));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        pnl_info_autor.add(jPanel2, gridBagConstraints);

        pnl_datos.add(pnl_info_autor, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnl_datos, java.awt.BorderLayout.LINE_END);

        tbl_autores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_autores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_autoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_autores);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_autoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_autoresMouseClicked
        // TODO add your handling code here:
        this.pnl_datos.setVisible(true);
    }//GEN-LAST:event_tbl_autoresMouseClicked

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        // TODO add your handling code here:
        this.pnl_datos.setVisible(false);
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
        // TODO add your handling code here:
        Validacion validacion = new Validacion();
        
        validacion.addTextBox(this.txt_nombre_completo, "nombre completo").addTextBox(this.txt_seudonimo, "seudonimo");
        
        validacion.validarSoloTexto(new String[]{ "nombre completo", "seudonimo" });
        
        if (!Validacion.isEmpty(txt_seudonimo) || !Validacion.isEmpty(txt_nombre_completo)) {
            if (validacion.validar()) {
                
            } else
                validacion.msgError("Modificar autor");
        } else
            Mensaje.error("Modificar autor", "Error: el nombre o el seudonimo debe de estar lleno");
    }//GEN-LAST:event_btn_modificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_author;
    private javax.swing.JLabel lbl_filtro_nombre_completo;
    private javax.swing.JLabel lbl_filtro_seudonimo;
    private javax.swing.JLabel lbl_nombre_completo;
    private javax.swing.JLabel lbl_seudonimo;
    private javax.swing.JPanel pnl_acciones;
    private javax.swing.JPanel pnl_datos;
    private javax.swing.JPanel pnl_info_autor;
    private javax.swing.JPanel pnl_opciones;
    private javax.swing.JTable tbl_autores;
    private javax.swing.JTextField txt_filtro_nombre_completo;
    private javax.swing.JTextField txt_filtro_seudonimo;
    private javax.swing.JTextField txt_nombre_completo;
    private javax.swing.JTextField txt_seudonimo;
    // End of variables declaration//GEN-END:variables
}
