/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cajero;

import java.math.BigDecimal;
import javax.swing.JOptionPane;

/**
 *
 * @author MekakuZero
 */
public class JFrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form JFrmMenu
     */
    org.tempuri.Cuentas cuenta;
    public JFrmMenu() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public JFrmMenu(org.tempuri.Cuentas cuenta) {
        initComponents();
        this.cuenta = cuenta;
        this.setTitle("Cuenta# " + cuenta.getNumeroCuenta());
        setLocationRelativeTo(null);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toolMenu = new javax.swing.JToolBar();
        btn_opcion_depocitar = new javax.swing.JButton();
        btn_opcion_retirar = new javax.swing.JButton();
        btn_opcion_saldo = new javax.swing.JButton();
        btn_cerrar_secion = new javax.swing.JButton();
        pnl_contenido = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_valor = new javax.swing.JTextField();
        btn_accion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setMaximumSize(new java.awt.Dimension(270, 180));
        setMinimumSize(new java.awt.Dimension(270, 180));
        setPreferredSize(new java.awt.Dimension(270, 180));
        setResizable(false);

        toolMenu.setRollover(true);

        btn_opcion_depocitar.setText("Depositar");
        btn_opcion_depocitar.setFocusable(false);
        btn_opcion_depocitar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_opcion_depocitar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_opcion_depocitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_opcion_depocitarActionPerformed(evt);
            }
        });
        toolMenu.add(btn_opcion_depocitar);

        btn_opcion_retirar.setText("Retirar");
        btn_opcion_retirar.setFocusable(false);
        btn_opcion_retirar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_opcion_retirar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_opcion_retirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_opcion_retirarActionPerformed(evt);
            }
        });
        toolMenu.add(btn_opcion_retirar);

        btn_opcion_saldo.setText("Ver saldo");
        btn_opcion_saldo.setFocusable(false);
        btn_opcion_saldo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_opcion_saldo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_opcion_saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_opcion_saldoActionPerformed(evt);
            }
        });
        toolMenu.add(btn_opcion_saldo);

        btn_cerrar_secion.setText("Cerrar secion");
        btn_cerrar_secion.setFocusable(false);
        btn_cerrar_secion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_cerrar_secion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_cerrar_secion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrar_secionActionPerformed(evt);
            }
        });
        toolMenu.add(btn_cerrar_secion);

        getContentPane().add(toolMenu, java.awt.BorderLayout.PAGE_START);

        jLabel1.setText("Monto total:");

        btn_accion.setText("Depositar");
        btn_accion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_accionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_contenidoLayout = new javax.swing.GroupLayout(pnl_contenido);
        pnl_contenido.setLayout(pnl_contenidoLayout);
        pnl_contenidoLayout.setHorizontalGroup(
            pnl_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_contenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_valor)
                    .addGroup(pnl_contenidoLayout.createSequentialGroup()
                        .addGroup(pnl_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(btn_accion))
                        .addGap(0, 146, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnl_contenidoLayout.setVerticalGroup(
            pnl_contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_contenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_accion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnl_contenido, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_opcion_saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_opcion_saldoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Saldo actual: " + cuenta.getSaldo() + "$");
    }//GEN-LAST:event_btn_opcion_saldoActionPerformed

    private void btn_opcion_depocitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_opcion_depocitarActionPerformed
        // TODO add your handling code here:
        this.btn_accion.setText("Depositar");
        this.txt_valor.setText("");
    }//GEN-LAST:event_btn_opcion_depocitarActionPerformed

    private void btn_opcion_retirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_opcion_retirarActionPerformed
        // TODO add your handling code here:
        this.btn_accion.setText("Retirar");
        this.txt_valor.setText("");
    }//GEN-LAST:event_btn_opcion_retirarActionPerformed

    private void btn_accionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_accionActionPerformed
        // TODO add your handling code here
        try {
            String valor = this.txt_valor.getText().trim();
        
            BigDecimal saldo = BigDecimal.valueOf(Double.valueOf(valor));
            
            String msg = "";

            if (this.btn_accion.getText().equals("Retirar"))
                msg = (Banco.retirar(cuenta.getNumeroCuenta(), saldo))? "Se ha retirado el saldo" : "No se ha`podido retirar el dinero";
            else
                msg = (Banco.depositar(cuenta.getNumeroCuenta(), saldo))? "Se ha depositado el saldo" : "No se ha`podido depositar el dinero";

            this.cuenta = Banco.iniciarSecion(cuenta.getNumeroCuenta());
            JOptionPane.showMessageDialog(null, msg + "\nSu saldo actual es: " + cuenta.getSaldo() + "$");
            this.txt_valor.setText("");
        } catch(Exception error) {
            JOptionPane.showMessageDialog(this, "Error: El valor del saldo es el incorecto", "Valor del saldo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_accionActionPerformed

    private void btn_cerrar_secionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrar_secionActionPerformed
        // TODO add your handling code here:
        JFrmLogin login = new JFrmLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_cerrar_secionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_accion;
    private javax.swing.JButton btn_cerrar_secion;
    private javax.swing.JButton btn_opcion_depocitar;
    private javax.swing.JButton btn_opcion_retirar;
    private javax.swing.JButton btn_opcion_saldo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnl_contenido;
    private javax.swing.JToolBar toolMenu;
    private javax.swing.JTextField txt_valor;
    // End of variables declaration//GEN-END:variables
}
