/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poo_catedra_2;

import javax.swing.JFrame;
import poo_catedra_2.autores.jfrm_Listar_Autores;
import poo_catedra_2.autores.jfrm_Nuevo_Autor;
import poo_catedra_2.libros.jfrm_Nuevo_Libro;
import poo_catedra_2.libros.jfrm_Listar_Libros;
import poo_catedra_2.usuarios.jfrm_Nuevo_Usuario;
import poo_catedra_2.usuarios.jfrm_Listar_Usuarios;

/**
 *
 * @author MekakuZero
 */
public class Sistema extends javax.swing.JFrame {

    /**
     * Creates new form sistema
     */
    private static jfrm_Nuevo_Usuario nuevo_Usuario;
    private static jfrm_Listar_Usuarios listar_usuarios;
    private static jfrm_Nuevo_Autor nuevo_Autor;
    private static jfrm_Listar_Autores listar_Autores;
    private static jfrm_Nuevo_Libro nuevo_libro;
    private static jfrm_Listar_Libros listar_Libros;
    
    public Sistema() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        usuariosMenu = new javax.swing.JMenu();
        crearUsuarioMenuItem = new javax.swing.JMenuItem();
        listarUsuariosMenuItem = new javax.swing.JMenuItem();
        autoresMenu = new javax.swing.JMenu();
        crearAutorMenuItem = new javax.swing.JMenuItem();
        listarAutorMenuItem = new javax.swing.JMenuItem();
        librosMenu = new javax.swing.JMenu();
        crearLibroMenuItem = new javax.swing.JMenuItem();
        listarLibroMenuItem = new javax.swing.JMenuItem();
        cerrarSesionMenuItem = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Control de libros");
        setMinimumSize(new java.awt.Dimension(983, 641));
        setPreferredSize(new java.awt.Dimension(983, 641));

        desktopPane.setPreferredSize(new java.awt.Dimension(741, 570));

        usuariosMenu.setMnemonic('f');
        usuariosMenu.setText("Usuarios");

        crearUsuarioMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poo_catedra_2/img/user_add.png"))); // NOI18N
        crearUsuarioMenuItem.setMnemonic('a');
        crearUsuarioMenuItem.setText("Crear usuarios");
        crearUsuarioMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearUsuarioMenuItemActionPerformed(evt);
            }
        });
        usuariosMenu.add(crearUsuarioMenuItem);

        listarUsuariosMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poo_catedra_2/img/user_list.png"))); // NOI18N
        listarUsuariosMenuItem.setMnemonic('x');
        listarUsuariosMenuItem.setText("Listar usuarios");
        listarUsuariosMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarUsuariosMenuItemActionPerformed(evt);
            }
        });
        usuariosMenu.add(listarUsuariosMenuItem);

        menuBar.add(usuariosMenu);

        autoresMenu.setMnemonic('e');
        autoresMenu.setText("Autores");

        crearAutorMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poo_catedra_2/img/autor_add.png"))); // NOI18N
        crearAutorMenuItem.setMnemonic('p');
        crearAutorMenuItem.setText("Crear autores");
        crearAutorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearAutorMenuItemActionPerformed(evt);
            }
        });
        autoresMenu.add(crearAutorMenuItem);

        listarAutorMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poo_catedra_2/img/autor_list.png"))); // NOI18N
        listarAutorMenuItem.setMnemonic('d');
        listarAutorMenuItem.setText("Listar autores");
        listarAutorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarAutorMenuItemActionPerformed(evt);
            }
        });
        autoresMenu.add(listarAutorMenuItem);

        menuBar.add(autoresMenu);

        librosMenu.setMnemonic('h');
        librosMenu.setText("Libros");

        crearLibroMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poo_catedra_2/img/book_add.png"))); // NOI18N
        crearLibroMenuItem.setMnemonic('c');
        crearLibroMenuItem.setText("Crear libros");
        crearLibroMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearLibroMenuItemActionPerformed(evt);
            }
        });
        librosMenu.add(crearLibroMenuItem);

        listarLibroMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poo_catedra_2/img/book_list.png"))); // NOI18N
        listarLibroMenuItem.setMnemonic('a');
        listarLibroMenuItem.setText("Listar libros");
        listarLibroMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarLibroMenuItemActionPerformed(evt);
            }
        });
        librosMenu.add(listarLibroMenuItem);

        menuBar.add(librosMenu);

        cerrarSesionMenuItem.setText("Opciones");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poo_catedra_2/img/exit.png"))); // NOI18N
        jMenuItem1.setText("Cerrar sesion");
        cerrarSesionMenuItem.add(jMenuItem1);

        menuBar.add(cerrarSesionMenuItem);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 983, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 641, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void listarUsuariosMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarUsuariosMenuItemActionPerformed
        if (listar_usuarios == null) {
            listar_usuarios = new jfrm_Listar_Usuarios();
            this.desktopPane.add(listar_usuarios);
            listar_usuarios.show();
        }
    }//GEN-LAST:event_listarUsuariosMenuItemActionPerformed

    private void crearUsuarioMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearUsuarioMenuItemActionPerformed
        // TODO add your handling code here:
        if (nuevo_Usuario == null) {
            nuevo_Usuario = new jfrm_Nuevo_Usuario();
            this.desktopPane.add(nuevo_Usuario);
            nuevo_Usuario.show();
        }
    }//GEN-LAST:event_crearUsuarioMenuItemActionPerformed

    private void crearAutorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearAutorMenuItemActionPerformed
        // TODO add your handling code here:
        if (nuevo_Autor == null) {
            nuevo_Autor = new jfrm_Nuevo_Autor();
            this.desktopPane.add(nuevo_Autor);
            nuevo_Autor.show();
        }
    }//GEN-LAST:event_crearAutorMenuItemActionPerformed

    private void listarAutorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarAutorMenuItemActionPerformed
        // TODO add your handling code here:
        if (listar_Autores == null) {
            listar_Autores = new jfrm_Listar_Autores();
            this.desktopPane.add(listar_Autores);
            listar_Autores.show();
        }
    }//GEN-LAST:event_listarAutorMenuItemActionPerformed

    private void crearLibroMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearLibroMenuItemActionPerformed
        // TODO add your handling code here:
        if (nuevo_libro == null) {
            nuevo_libro = new jfrm_Nuevo_Libro();
            this.desktopPane.add(nuevo_libro);
            nuevo_libro.show();
        }
    }//GEN-LAST:event_crearLibroMenuItemActionPerformed

    private void listarLibroMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarLibroMenuItemActionPerformed
        // TODO add your handling code here:
        if (listar_Libros == null) {
            listar_Libros = new jfrm_Listar_Libros();
            this.desktopPane.add(listar_Libros);
            listar_Libros.show();
        }
    }//GEN-LAST:event_listarLibroMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sistema.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sistema().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu autoresMenu;
    private javax.swing.JMenu cerrarSesionMenuItem;
    private javax.swing.JMenuItem crearAutorMenuItem;
    private javax.swing.JMenuItem crearLibroMenuItem;
    private javax.swing.JMenuItem crearUsuarioMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu librosMenu;
    private javax.swing.JMenuItem listarAutorMenuItem;
    private javax.swing.JMenuItem listarLibroMenuItem;
    private javax.swing.JMenuItem listarUsuariosMenuItem;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu usuariosMenu;
    // End of variables declaration//GEN-END:variables

}
